### ISSUE TITLE
Docstring conventions for one-liners

### ISSUE THREAD

**Issue by hugolundin** [teknik-eksjo/datastrukturer#7]
According to PEP 0257, oneliner docstrings should be formatted like this:

``` python
def function():
    """This is a one line docstring"""
   pass
```

Right now, oneliner docstrings are formatted like this:

``` python
def function():
    """This is a one line docstring
    """
   pass
```

**Comment by Limpan** [comment]
Maybe we need the plugin flake8-docstrings?

**Comment by Limpan** [comment]
I find that the flake8-docstrings plugin give a few weird errors. Maybe it's too rigid? Can @hugolundin make `list.py` conform to PEP257? Then we have an example to base our decision on.

Since D203 and D211 are conflicting I propose to solve the issue by ignoring D203.

**Comment by Limpan** [comment]
Added docstring linting with commit a84ff9b.
